### ISSUE TITLE
"http://memorial.servegame.com" not found

### ISSUE THREAD

**Issue by Rhymmor** [nev3rfail/baranov-memorial#1]
Сейчас если попытаться зайти на http://memorial.servegame.com/ без добавления index.html, то кинет 404 ошибку.

Не уверен на чем хостишь, в хедерах видно и PHP, и Nginx, так бы прислал PR для nginx.conf

**Comment by nev3rfail** [comment]
Всё верно, там php-fpm и мне было лень разбираться с правами. Сейчас вообще его отключу, всё равно уже принято решение клепать html+js без серверсайда.

**Comment by nev3rfail** [comment]
Исправлено, закрываю.
